name: Master Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: pull latest from ec2
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} -i ${{ secrets.AWS_KEY }}
        cd track-square
        git pull
        sudo npm install -g npm@latest
        sudo npm install
        npm run build
        
        cd /home/ubuntu/track-square/server
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

        sudo systemctl daemon-reload
        sudo systemctl start track-square
        sudo systemctl start nginx
        sudo systemctl reload nginx
